### ISSUE TITLE
Unable to find pyserini docker

### ISSUE THREAD

**Issue by cadurosar** [UKPLab/beir#16]
Hi, I'm trying to experiment with beir, BM25 and pyserini, but I'm unable to find the docker image (beir/beir-pyserini). Looking at dockerhub (https://hub.docker.com/u/beir) it seems that the only image available is pyserini-fastapi. 

Is pyserini-fastapi the same as beir-pyserini or there is something that I'm doing wrong?

**Comment by NThakur20** [comment]
Hi @cadurosar,

Both are actually the same. So you can use ``docker pull beir/pyserini-fastapi`` to get the latest docker image.
``beir-pyserini`` was the original (old) docker image name but it was not a great name so I renamed it ``pyserini-fastapi``. 

Thanks for pointing this out, I missed updating the image names in the BEIR examples. I will do that. 

Kind Regards,
Nandan
