### ISSUE TITLE
init_weights error when loading DPR models from HF modelhub

### ISSUE THREAD

**Issue by Timoeller** [UKPLab/beir#17]
Congrats on this very well structured, documented and helpful framework for figuring out whats going on in IR - especially on OOD data. Keep up the good work!

When loading DPR models from HF modelhub like:

```python
model = DRES(models.SentenceBERT((
    "facebook/dpr-question_encoder-multiset-base",
    "facebook/dpr-ctx_encoder-multiset-base",
    " [SEP] "), batch_size=128))
```

I run into an `NotImplementedError: Make sure `_init_weigths` is implemented for <class 'transformers.models.dpr.modeling_dpr.DPRQuestionEncoder'>`

I know you converted the model to a sentencetransformers already and can be loaded like this but an interoperability with the HF hub would be slick - also for other DPR models in other languages like [French](https://huggingface.co/etalab-ia/dpr-question_encoder-fr_qa-camembert) or [German](https://huggingface.co/deepset/gbert-base-germandpr-ctx_encoder).

Thanks

**Comment by NThakur20** [comment]
Hi @Timoeller, 

Added support to evaluate HF DPR models, you can load using this snippet below:
```python
model = DRES(models.DPR((
    "facebook/dpr-question_encoder-multiset-base",
    "facebook/dpr-ctx_encoder-multiset-base"), batch_size=128))
```
Also works with deepset.ai GermanDPR model,
```python
model = DRES(models.DPR((
    "deepset/gbert-base-germandpr-question_encoder",
    "deepset/gbert-base-germandpr-ctx_encoder"), batch_size=128))
```
I would push the updates to the latest pip version hopefully soon. Until then you can download the repository and run it locally if required.

Kind Regards,
Nandan

**Comment by Timoeller** [comment]
Thanks for the fix, tested on current master and it works.
