### ISSUE TITLE
Add BM25+RM3 as a baseline to re-ranking leaderboard

### ISSUE THREAD

**Issue by joshdevins** [UKPLab/beir#19]
We see this approach in the "[dense leaderboard](https://docs.google.com/spreadsheets/d/1L8aACyPaXrL8iEelJLGqlMqXKPX2oSP_R10pZoy77Ns/edit#gid=0)", but it would be good to add a row to the "[re-ranking leaderboard](https://docs.google.com/spreadsheets/d/1L8aACyPaXrL8iEelJLGqlMqXKPX2oSP_R10pZoy77Ns/edit#gid=867044147)" for easier comparisons against baselines.

**Comment by NThakur20** [comment]
Hi @joshdevins,
Nice suggestion! I would copy and paste the row to the reranking leaderboard.

Kind Regards,
Nandan Thakur

**Comment by NThakur20** [comment]
This has been updated here: https://docs.google.com/spreadsheets/d/1L8aACyPaXrL8iEelJLGqlMqXKPX2oSP_R10pZoy77Ns/edit#gid=867044147

Kind Regards,
Nandan
