### ISSUE TITLE
Separate average score for zero-shot only

### ISSUE THREAD

**Issue by joshdevins** [UKPLab/beir#20]
Between the two [leaderboard](https://docs.google.com/spreadsheets/d/1L8aACyPaXrL8iEelJLGqlMqXKPX2oSP_R10pZoy77Ns/edit#gid=867044147) tabs, they are laid out slightly differently. It would be nice to normalize these or put them on a single tab. If anything, just separating the "average" score to only include zero-shot methods in the "re-ranking leaderboard" would help compare across tabs. Basically the same view as is in the paper is preferred.

**Comment by NThakur20** [comment]
Hi @joshdevins, 

Yes, I need to change the layout of the reranking table comparable to the dense one, it has been on my todo list now since forever. Will do that soon and update you once it has been done!

Kind Regards,
Nandan

**Comment by NThakur20** [comment]
This has been updated here: https://docs.google.com/spreadsheets/d/1L8aACyPaXrL8iEelJLGqlMqXKPX2oSP_R10pZoy77Ns/edit#gid=867044147

Kind Regards,
Nandan

**Comment by joshdevins** [comment]
Look amazing, thank you!
