### ISSUE TITLE
DPR on MSMARCO

### ISSUE THREAD

**Issue by JetRunner** [UKPLab/beir#27]
Hi! Thanks for sharing BEIR - this is a wonderful project!

I wonder if you can include DPR model trained on MSMARCO on the [leaderboard](https://docs.google.com/spreadsheets/d/1L8aACyPaXrL8iEelJLGqlMqXKPX2oSP_R10pZoy77Ns/edit#gid=0)? The current DPR (Multi) and DPR (KILT) are not really comparable with other models which are trained on MARCO.

Thanks!

**Comment by NThakur20** [comment]
Hi @JetRunner,

Unfortunately, I do not have a DPR model trained on the MS MARCO dataset. The original DPR code requires 8 V100 GPUs for training and I personally have access to only a few GPUs at max in my lab. 

What is really interesting is the Gradient Caching Technique (https://arxiv.org/abs/2101.06983) introduced by @luyug which I plan to hopefully integrate soon within BEIR. This will allow you to train a DPR system using a single V100 GPU within 11GB.

Once we have GradCache (https://github.com/luyug/GradCache) included within the repository, I could share a trained DPR model on the MSMARCO dataset.

 Kind Regards,
Nandan

**Comment by JetRunner** [comment]
Thanks, @NThakur20!
