### ISSUE TITLE
Additional annotations for Trec-covid

### ISSUE THREAD

**Issue by ji-xin** [UKPLab/beir#38]
Just saw the submission to Neurips (https://openreview.net/forum?id=wCu6T5xFjeJ), great work!
I was just wondering whether you plan to release the additional annotations for Trec-covid’s hole filling? Thanks!

**Comment by nreimers** [comment]
Hi @ji-xin 
That was quick to notice.

In the appendix (sadly a separate file for the NeuRIPS submission) the link is provided:
https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/trec-covid-beir.zip

**Comment by ji-xin** [comment]
Thanks!
