### ISSUE TITLE
About webis-touche2020 qrels

### ISSUE THREAD

**Issue by guoday** [UKPLab/beir#40]
Thanks for your great works. I notice that average number of docs per query changes from 49.9 to 19.0 in your latest version of the paper. To keep the same setting as your, what should I need to do?

Thanks.

**Comment by NThakur20** [comment]
Hi @guoday,

Nice observation! I was wondering when I will get this issue. I used the latest version of webis-touche2020 qrels which the dataset authors recently provided for the paper. I was waiting for the numbers on the leaderboard (exps which I need to rerun), and then upload the latest dataset.

Anyways, I will upload the latest dataset soon and update you back here once its done!

Kind Regards,
Nandan Thakur

**Comment by guoday** [comment]
Thanks a lot for your reply. 😊

**Comment by NThakur20** [comment]
All done, you can find the latest dataset here: https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/webis-touche2020.zip

Kind Regards,
Nandan

**Comment by guoday** [comment]
Thanks for your quick action!!!

Best,
Daya
