### ISSUE TITLE
Missing datasets

### ISSUE THREAD

**Issue by thigm85** [UKPLab/beir#61]
Hi, it seems that some datasets that are on the leaderboard are missing from https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/

For example:
* `bioasq`
* `signallm`
* `trec-news` 

Is there a reason for removing those datasets?

**Comment by NThakur20** [comment]
Hi @thigm85, 

I do not have permissions to freely open-source and provide these datasets due their individual licence policies. You can check on how to replicate them yourself from the README file here: https://github.com/UKPLab/beir/tree/main/examples/dataset.

Kind regards,
Nandan

**Comment by thigm85** [comment]
Thanks for the quick response. I got it :)
