### ISSUE TITLE
Datasets without Download Links

### ISSUE THREAD

**Issue by sclincha** [UKPLab/beir#7]
Hello,
 Thanks for your great work  !
 I am just curious how can we reproduce some results and get the bioasq, signal1m etc  ...  datasets to work with beir.
 (currently testing our own model on beir  ! )

**Comment by NThakur20** [comment]
Hello @sclincha ,

I need to still add instructions for datasets not publicly available yet in the benchmark. 
Few are a bit complicated (Signal1M) would add details on how to implement them hopefully soon in the benchmark.

If you want them immedeately, please write me an email (nandant@gmail.com) and I can personally share instructions for reproduction.

**Comment by sclincha** [comment]
ok Great I will write to you !
