### ISSUE TITLE
CQAdupstack evaluation

### ISSUE THREAD

**Issue by cadurosar** [UKPLab/beir#9]
First I would like to thank you for this incredible framework, it has been of incredible help to me. 

I have a question concerning the cqadupstack results. As there are 12 different corpus for that dataset, which mean did you used to compute your results? The mean of means (i.e. each dataset has equal weight) or the mean over all the queries (i.e. each query has equal weight)?

Thanks in advance.

**Comment by NThakur20** [comment]
Hi @cadurosar, Thank you for your kind words!

We considered the mean of means for cqadupstack with each domain/corpus having equal weight. 
In short, the final ``NDCG@10`` score becomes``= sum(NDCG@10 for each domain) / 12`` in cqadupstack.

Kind Regards,
Nandan

**Comment by cadurosar** [comment]
Great, thanks for your quick answer! :)

**Comment by joshdevins** [comment]
Can/should we add a link to this ticket from the README somewhere? Seems people will run into this again.
